/* ADD DATA */

/*	BRANDS*/
INSERT INTO _BRAND VALUES	('Barcel')
INSERT INTO _BRAND VALUES	('Bimbo')
INSERT INTO _BRAND VALUES	('Bokados')
INSERT INTO _BRAND VALUES	('Coca Cola')
INSERT INTO _BRAND VALUES	('Gamesa')
INSERT INTO _BRAND VALUES	('Tia Rosa')
INSERT INTO _BRAND VALUES	('Sabritas') 
INSERT INTO _BRAND VALUES	('PEPSI')
INSERT INTO _BRAND VALUES	('Alsamar')
GO

/*	CATEGORY */
INSERT INTO _CATEGORY
VALUES('Lacteos')
INSERT INTO _CATEGORY
VALUES('Botanas')
INSERT INTO _CATEGORY
VALUES('Carnes Fritas')
INSERT INTO _CATEGORY
VALUES( 'Miscelanea')
INSERT INTO _CATEGORY
VALUES( 'Aceites')


/* PRODUCTS */
INSERT INTO PRODUCT VALUES( 2, 1, 'Chips', 20, 5),( 2, 1, 'Takis fuego anal', 10, 20), ( 1, 4, 'VIO', 15, 16)
